services:
  postgres_db:
    container_name: postgres_db
    image: postgres:17.2
    environment:
      POSTGRES_USER: deliverease_db_user
      POSTGRES_PASSWORD: deliverease_db_pass
      POSTGRES_DB: deliverease_db
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U deliverease_db_user -d deliverease_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  application:
    container_name: application
    image: ghcr.io/stoyanchorbov/deliverease-backend:latest
#    build:
#      context: .
#      dockerfile: Application/Dockerfile
    pull_policy: always
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=deliverease_db
      - DB_USER=deliverease_db_user
      - DB_PASS=deliverease_db_pass
#    ports:
#      - "5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`schorbov.eu`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.strip-api-path.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=strip-api-path"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - backend
      - web_app

#  view:
#    container_name: web_view
#    image: ghcr.io/stoyanchorbov/deliverease-nuxt:latest
#    pull_policy: always
#    ports:
#      - "3000:3000"
#    depends_on:
#      - application
#    networks:
#      - web_app

networks:
  backend:
  web_app:

volumes:
  db_data:
